### ISSUE TITLE
Please create /employee login page as like mentioned below

### ISSUE THREAD

**Issue by roy-einstein** [joynewton1996/Webportal#6]
![image](https://user-images.githubusercontent.com/32195027/118591463-d381c380-b7c1-11eb-972d-5e37fbfce9f2.png)

**Comment by joynewton1996** [comment]
solved 
![employee login](https://user-images.githubusercontent.com/82137922/119146810-a0ad2900-ba68-11eb-9844-8eae4400d281.jpg)

**Comment by roy-einstein** [comment]
it doesn't use same format compared to other pages,

**Comment by joynewton1996** [comment]
![employee login](https://user-images.githubusercontent.com/82137922/119855316-6c85ac80-bf2f-11eb-860f-e66980a65c65.jpg)
