### ISSUE TITLE
create /employee_serach

### ISSUE THREAD

**Issue by roy-einstein** [joynewton1996/Webportal#7]
![image](https://user-images.githubusercontent.com/32195027/118591769-64589f00-b7c2-11eb-8907-ee6312099bcb.png)

**Comment by joynewton1996** [comment]
![employee_search](https://user-images.githubusercontent.com/82137922/120018733-33b80700-c005-11eb-9169-ea848daa0f88.jpg)

**Comment by roy-einstein** [comment]
please update the Pr
