### ISSUE TITLE
Create /employee_register page

### ISSUE THREAD

**Issue by roy-einstein** [joynewton1996/Webportal#9]
Create Page, which takes few inputs,

1. first name
2.  last name
3.  Address
4. ph.no
5. DOB
6. Year of passout,
7. Highest qualification

<register> button

**Comment by joynewton1996** [comment]
![empployee_registration](https://user-images.githubusercontent.com/82137922/120186597-56c6fe80-c231-11eb-8307-30a732732355.jpg)

**Comment by roy-einstein** [comment]
Employee data to be loaded, Use the column headers as input boxes
[employees.csv](https://github.com/joynewton1996/Webportal/files/6571447/employees.csv)
